### ISSUE TITLE
LOCATION_CHANGED action doesn't remember the query when going back (POP)

### ISSUE THREAD

**Issue by merisbahti** [FormidableLabs/redux-little-router#233] opened 2017-09-22 10:15 UTC
When moving back to a location with query-parameters, the router seems to have omitted the query-parameters the initial LOCATION_CHANGED-action was called with (even though the POP-action has the query-parameters)

I've included below which actions have to be dispatched to reproduce the issue.
```
ROUTER_LOCATION_CHANGED {param: "foo"}
ROUTER_PUSH {param: "bar"}
ROUTER_LOCATION_CHANGED {param: "bar"}
ROUTER_POP {param: "foo"}  // Why does this have {param: "foo"} and the next action doesn't?
ROUTER_LOCATION_CHANGED undefined  // Expected: ROUTER_LOCATION_CHANGED {param: "foo"}
```

**Comment by jahed** [comment] 2017-10-14 15:01
Same as #211

**Comment by tptee** [comment] 2017-10-18 22:40
Yep, duplicate of #211 which is a high-pri bug!

**Closed** 2017-10-18 22:40 UTC
