### ISSUE TITLE
Fragments can't access this.context

### ISSUE THREAD

**Issue by elisechant** [FormidableLabs/redux-little-router#191] opened 2017-06-20 00:01 UTC
# Steps to reproduce

1. download this repo, and open demo files.
2. `npm install -S redux-little-router`
3. open `demo/client/demo.js:6`. change this line:

`import { Link, Fragment } from '../../src';` to:

`import { Link, Fragment } from 'redux-little-router;`

4. Run the demo in browser

This error is visible in the console: 

```
Uncaught TypeError: Cannot read property 'store' of undefined
    at RelativeFragment.render (main.js:30478)
    at main.js:15901
    at measureLifeCyclePerf (main.js:15180)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (main.js:15900)
    at ReactCompositeComponentWrapper._renderValidatedComponent (main.js:15927)
    at ReactCompositeComponentWrapper.performInitialMount (main.js:15467)
    at ReactCompositeComponentWrapper.mountComponent (main.js:15363)
    at Object.mountComponent (main.js:7901)
    at ReactDOMComponent.mountChildren (main.js:14493)
    at ReactDOMComponent._createInitialChildren (main.js:11555)
```

**Comment by justrossthings** [comment] 2017-06-20 12:43
NPM's stored package is broke?

I built & tested dist-min, dist-dev, lib and was able to get demo running fine, bar this unrelated warning from build-dist-min:
```
warning.js:36 Warning: Failed context type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in r (created by Connect(r))
    in Connect(r) (created by Demo)
    in div (created by Demo)
    in Demo (created by Connect(Demo))
    in Connect(Demo)
    in Provider
```

**Comment by EmrysMyrddin** [comment] 2017-06-21 14:14
Yes, NPM's package is broken. I have manually compiled it in my project and it solved the problem...

**Comment by tomciopp** [comment] 2017-06-21 16:11
I am running into a similar issue with `Link` @justrossthings @EmrysMyrddin any tips for troubleshooting? I've also noticed that the code that breaks has been changed to remove the reference to `context` in the last few commits, is there any chance that a patch version can be released?

**Comment by therealpineda** [comment] 2017-06-21 16:40
@EmrysMyrddin or @justrossthings how does one manually compile the npm package? 😅

**Comment by shepmaster** [comment] 2017-06-21 18:47
I believe the problem is that you are reading **master**s documentation but using the released version **13.2.0**. You can see the documentation at https://github.com/FormidableLabs/redux-little-router/tree/v13.2.0. Specifically, I needed to wrap my app in  `<Provider>`

```diff
  <Provider store={store}>
+    <RouterProvider store={store}>
       <MyApp />
+   </RouterProvider>
  </Provider>
```

**Comment by justrossthings** [comment] 2017-06-22 00:43
@therealpineda @tomciopp you can pull the redux-little-router (RLR) repo then run `yarn install && yarn build-dist`. You should find a dist folder in the RLR root folder with RLR.min.js

@shepmaster I thought 13.2 had removed RouterProvider?
 https://github.com/FormidableLabs/redux-little-router/pull/189

**Comment by shepmaster** [comment] 2017-06-22 01:27
@justrossthings looking at the [README for 13.2.0](https://github.com/FormidableLabs/redux-little-router/tree/v13.2.0) I linked to, there's an entire [section describing `RouterProvider`](https://github.com/FormidableLabs/redux-little-router/tree/v13.2.0#providerouter-or-routerprovider), and the [code is still there](https://github.com/FormidableLabs/redux-little-router/blob/v13.2.0/src/components/provider.js#L65).

**Comment by tptee** [comment] 2017-06-22 02:40
I merged README updates for an unreleased PR 🤦‍♂️ I'll cut a release with the updates (which does remove RouterProvider)

**Comment by elisechant** [comment] 2017-06-22 20:25
@tptee can you publish 14.0.0 to npm as well? 

In the meantime I can confirm that @shepmaster's snippet about using `<RouterProvider` is a valid workaround for now, but it is pretty ugly:

```
ReactDOM.render(
  <Provider store={store}>
    <RouterProvider store={store}>
      <Root />
```

**Comment by dskoda1** [comment] 2017-06-28 22:39
Getting the documentation in sync would be nice, I banged my head against my computer for a day or two before finding this. 

I also think having things crucial to initial setup like the `RouterProvider` was for 13.2 probably should've been higher up in the documentation - it was all the way at the bottom. Just thoughts going forward.

**Comment by tptee** [comment] 2017-07-03 02:33
Sorry about the delay, `v14` is out and the docs are in sync!

**Closed by tptee** 2017-07-03 02:33 UTC

**Comment by therealpineda** [comment] 2017-07-11 01:21
never thanked you all. im getting around to using this again in a project soon and very grateful for your help and work here 👍 👍 👍  ❤️  @tptee @shepmaster @justrossthings @elisechant
